Cosmos DB に繋がらない場合
jpcosmosdb/blog pull request #10
Opened 2023-03-29 02:34 UTC by shoshii

Cosmos DB for NoSQL に繋がらない場合、サービスに原因があるかクイックに確認する方法を案内するのを目的としています。
お忙しいところ恐縮ですが、レビューをお願いします。

2023-04-01 03:26 UTC, yokofms commented
/ok-to-preview sha=a3173791

2023-04-03 01:19 UTC, takumasa0222 reviewed
下記コメントいたしました。ご確認お願い致します。

2023-04-03 01:19 UTC, takumasa0222 commented on themes/jpazure
こちらは削除いただけると幸いです

2023-04-03 01:19 UTC, takumasa0222 commented on articles/CosmosDB/トラブルシューティング/Cosmos-DB-initialtsg.md
> +> Cosmos DB .NET/Java SDK は、診断情報として接続先のレプリカ情報や、詳細なエラーコード、クライアント側のリソース情報（ＣＰＵやメモリの使用率）も含めて出力します。
```suggestion
> Cosmos DB .NET/Java SDK は、診断情報として接続先のレプリカ情報や、詳細なエラーコード、クライアント側のリソース情報（CPU やメモリの使用率）も含めて出力します。
```

2023-04-03 01:19 UTC, takumasa0222 commented on articles/CosmosDB/トラブルシューティング/Cosmos-DB-initialtsg.md
> +
```suggestion
<!--more-->
```
こちらを入れていただけると見栄えがすっきりすると思います。

2023-04-03 01:19 UTC, takumasa0222 commented on articles/CosmosDB/トラブルシューティング/Cosmos-DB-initialtsg.md
> +
```suggestion
> [!WARNING]
> Azure サービスの状態はリージョン全体で問題が発生している場合に更新されます。個別の Cosmos DB アカウントが不調な場合は、まずCosmos DB の可用性をご確認ください。

```
すこし追記いたしました。下記の様な感じで見えます。
![AddCaution](https://user-images.githubusercontent.com/37662590/229391067-688c9e6f-169f-4f5c-8935-e65b434117a3.png)

2023-04-03 03:21 UTC, shoshii commented on themes/jpazure
削除しましたー

2023-04-03 03:29 UTC, shoshii commented
/ok-to-preview sha=a3173791

2023-04-03 05:30 UTC, shoshii commented
情報採取手順へのリンクと、submodule について修正しました。

2023-04-03 06:29 UTC, takumasa0222 approved these changes
そのほか問題ないと思います。ありがとうございます！

2023-04-03 06:29 UTC, takumasa0222 commented on articles/CosmosDB/トラブルシューティング/Cosmos-DB-initialtsg.md
> +> Azure サービスの状態はリージョン全体で問題が発生している場合に更新されます。個別の Cosmos DB アカウントが不調な場合は、まずCosmos DB の可用性をご確認ください。
```suggestion
> Azure サービスの状態はリージョン全体で問題が発生している場合に更新されます。個別の Cosmos DB アカウントが不調な場合は、まず Cosmos DB の可用性をご確認ください。
```
自分のコメントに自分で修正入れる形ですみません、、

2023-04-03 10:25 UTC, yokofms requested changes
いくつか修正案を記載しました。ご確認ください！

2023-04-03 10:25 UTC, yokofms commented on articles/CosmosDB/トラブルシューティング/Cosmos-DB-initialtsg.md
> +本記事では アプリケーションから Cosmos DB for NoSQL に繋がらない場合、問題が Cosmos DB サービス側に起因するか否かの切り分け方法をご案内します。
```suggestion
本記事では アプリケーションから Cosmos DB に繋がらない場合、問題が Cosmos DB サービス側に起因するか否かの切り分け方法をご案内します。
なお SDK 観点の確認は Cosmos DB for NoSQL についての案内となっています。
```

2023-04-03 10:25 UTC, yokofms commented on articles/CosmosDB/トラブルシューティング/Cosmos-DB-initialtsg.md
> +本記事では アプリケーションから Cosmos DB for NoSQL に繋がらない場合、問題が Cosmos DB サービス側に起因するか否かの切り分け方法をご案内します。
可用性の確認は Cosmos DB for NoSQL に限った確認ではないためカットしました。

2023-04-03 10:25 UTC, yokofms commented on articles/CosmosDB/トラブルシューティング/Cosmos-DB-initialtsg.md
> +分析情報＞可用性タブ にて、 Cosmos DB アカウントの可用性の情報をご確認可能です。
```suggestion
分析情報＞可用性タブ にて、 Cosmos DB アカウントの可用性が確認可能です。
```

2023-04-03 10:25 UTC, yokofms commented on articles/CosmosDB/トラブルシューティング/Cosmos-DB-initialtsg.md
> +分析情報＞可用性タブ にて、 Cosmos DB アカウントの可用性の情報をご確認可能です。
好みですがシンプルにしてみました。

2023-04-03 10:25 UTC, yokofms commented on articles/CosmosDB/トラブルシューティング/Cosmos-DB-initialtsg.md
> +数分間以上この状態が継続してしまっている場合、お手数ですが、Azure サポートまでお問い合わせください。
```suggestion
数分間以上この状態が継続している場合、後述の [Azure の状態](https://azure.status.microsoft/ja-jp/status) で問題が発生しているかご確認ください。

次の方法で Azure サポートまでお問い合わせ可能です。

[Cosmos DB サポートへのお問い合わせ](https://learn.microsoft.com/ja-jp/azure/azure-portal/supportability/how-to-create-azure-support-request)　
```

2023-04-03 10:25 UTC, yokofms commented on articles/CosmosDB/トラブルシューティング/Cosmos-DB-initialtsg.md
> +お手数ですが、Azure サポートまでお問い合わせください。
```suggestion
問題が発生しているサービス・リージョンの障害情報は随時  [Azure の状態](https://azure.status.microsoft/ja-jp/status) で情報を提供しております。

```

2023-04-04 00:32 UTC, shoshii commented on articles/CosmosDB/トラブルシューティング/Cosmos-DB-initialtsg.md
> +お手数ですが、Azure サポートまでお問い合わせください。
ご指摘ありがとうございます。

修正後の記述ですと以下の懸念があるので、原案のままでいきたいのですがいかがでしょうか？

* サービス障害が発生している場合にお客様がなにをすべきかわからない（Azureの状態には、お客様が何をすべきかは記述されていなかったと思います）
* 可用性のSLAに違反していてかつサービス障害が発生していた場合、以下の記述に矛盾すると思います

Solution 2: It did violate the Azure Cosmos DB SLA
Contact [Azure Support](https://aka.ms/azure-support)
https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/troubleshoot-request-timeout

2023-04-04 08:58 UTC, yokofms commented
/ok-to-preview sha=625b88f

2023-04-04 09:21 UTC, shoshii commented
/ok-to-preview sha=bfa5e92

2023-04-04 09:27 UTC, shoshii commented
ご確認ありがとうございます。ご指摘を取り込んだうえ、プレビューに反映しました。

2023-04-04 09:35 UTC, yokofms approved these changes
Looks good. Thank you!

2023-04-04 09:44 UTC, merged