Logicapp
jpcosmosdb/blog pull request #12
Opened 2023-05-22 03:20 UTC by shoshii

Cosmos DB NoSQL API のデータを LogicApp (コーディングなし) で一括更新する方法です。
日本語でまとまった記事はなかったので特定のケースで有用かと思います。レビューをお願いいたします。

2023-06-02 09:04 UTC, takumasa0222 reviewed
細かいところや実際に実装してみてわかりづらかった点を補記しました。
実際の挙動についてはエラーが出てしまっているので後日確認させてください。

2023-06-02 09:04 UTC, takumasa0222 commented on articles/CosmosDB/HowTo/bulkupdate-logicapp.md
> +
```suggestion
<!--more-->
```

2023-06-02 09:04 UTC, takumasa0222 commented on articles/CosmosDB/HowTo/bulkupdate-logicapp.md
> +これらのドキュメントの「time」を現在時刻に更新し、かつ「age」に +1 をする処理を Logic Apps と Cosmos DB のストアドプロシージャを用いて実装してみます。
```suggestion
これらのドキュメントの「time」を現在時刻に更新し、かつ「age」に +1 をする処理を Logic Apps と Cosmos DB のストアド プロシージャを用いて実装してみます。
```

2023-06-02 09:04 UTC, takumasa0222 commented on articles/CosmosDB/HowTo/bulkupdate-logicapp.md
> +今回の例では、 Cosmos DB NoSQL API のコレクション（コレクション ID: users ) に以下の 2 ドキュメントが格納されているとします。パーティション キーは「name」です。
```suggestion
今回の例では、 Cosmos DB NoSQL API のコレクション (コレクション ID: users) に以下の 2 ドキュメントが格納されているとします。パーティション キーは「name」です。
```

2023-06-02 09:30 UTC, takumasa0222 reviewed
こちら追加が漏れていましたので

2023-06-02 09:30 UTC, takumasa0222 commented on articles/CosmosDB/HowTo/bulkupdate-logicapp.md
> +任意の接続名と、操作対象の Cosmos DB アカウント名、プライマリーキーの値を設定します。
```suggestion
任意の接続名と、操作対象の Cosmos DB アカウント名、プライマリー キーの値を設定します。
```

2023-06-02 09:30 UTC, takumasa0222 commented on articles/CosmosDB/HowTo/bulkupdate-logicapp.md
> +検索窓に「JSON」を入力し、「ビルトイン」タブから「JSON の解析」を選択します。
```suggestion
「アクションの追加」をクリック後、検索窓に「JSON」を入力し、「ビルトイン」タブから「JSON の解析」を選択します。
```

2023-06-02 09:30 UTC, takumasa0222 commented on articles/CosmosDB/HowTo/bulkupdate-logicapp.md
> +コンテンツに「現在のアイテム」を指定します。
```suggestion
コンテンツに動的なアイテムの追加より「現在のアイテム」を指定します。
```

2023-06-02 09:30 UTC, takumasa0222 commented on articles/CosmosDB/HowTo/bulkupdate-logicapp.md
> +次に、「ストアド プロシージャのパラメーター」を選択します。
```suggestion
次に、新しいパラメーターの追加より「ストアド プロシージャのパラメーター」を選択します。
```

2023-06-03 06:18 UTC, yokofms reviewed
修正案を追記しました。ストアドプロシージャーを実行(V2) のスクリーンショットの置き換えと追加についてもコメントしていますのでお手すきの際にご確認ください。

2023-06-03 06:18 UTC, yokofms commented on articles/CosmosDB/HowTo/bulkupdate-logicapp.md
> +コンテンツに「現在のアイテム」を指定します。
```suggestion
JSON の解析のコンテンツに動的なアイテムの追加より For each 配下の「現在のアイテム」を指定します。
```

2023-06-03 06:18 UTC, yokofms commented on articles/CosmosDB/HowTo/bulkupdate-logicapp.md
> +新しいパラメーターの追加より「パーティション キーの値」を選択し、パーティション キーの値を指定します。この例のコレクションにおいては、パーティション キーは name なので、 「JSON の解析」から 「name」 を選択します。
```suggestion
新しいパラメーターの追加より「パーティション キーの値」を選択し、パーティション キーの値を指定します。この例のコレクションにおいては、パーティション キーは name なので、 「JSON の解析」から 「name」 を選択します。
「name」はダブルクォートで囲みます。
```

2023-06-03 06:18 UTC, yokofms commented on articles/CosmosDB/HowTo/bulkupdate-logicapp.md
> +この時、それぞれの引数の値をダブルクォートで囲む必要がありますので、ご注意ください。
```suggestion
今回のストアドプロシージャーのパラメーターは ["<_self>","<utcNow()>"]  と角括弧で全体を囲み、_self, utcNow() それぞれの引数の値はそれぞれダブルクォートで囲む必要がありますので、ご注意ください。
```

2023-06-03 06:18 UTC, yokofms commented on articles/CosmosDB/HowTo/bulkupdate-logicapp.md
> +この時、それぞれの引数の値をダブルクォートで囲む必要がありますので、ご注意ください。
ストアドプロシージャーのパラメーターのスクリーンショットを角括弧が見えるものに置き換えと、追加でストアドプロシージャーを実行の全般の設定が確認できるスクリーンショットの追加をご検討ください。

2023-06-05 00:56 UTC, shoshii commented
@yokofms @takumasa0222 ご確認ありがとうございます。修正内容反映しました。ストアドのパラメーターをカッコでくくる件も画像も差し替えました。

2023-06-05 00:58 UTC, shoshii commented
/ok-to-preview sha=1d92375

2023-06-05 02:37 UTC, shoshii commented
/ok-to-preview sha=8a037ec

2023-06-05 04:42 UTC, yokofms commented
/ok-to-preview sha=8a037ec

2023-06-05 05:26 UTC, yokofms requested changes
articles/CosmosDB/HowTo/bulkupdate-logicapp/cosmos-dexp-sprg.png　の上部 'データエクスプローラー' の左横に表示されているアカウント名もマスクください。他よいとおもいます！

2023-06-05 05:26 UTC, yokofms commented on articles/CosmosDB/HowTo/bulkupdate-logicapp/cosmos-dexp-sprg.png
上部  'データエクスプローラー' の左横に表示されているアカウント名もマスクください。

2023-06-16 02:52 UTC, shoshii commented
/ok-to-preview sha=a89115b

2023-06-16 05:01 UTC, yokofms commented
/ok-to-preview sha=a89115b

2023-06-23 04:52 UTC, takumasa0222 approved these changes

2023-06-23 05:31 UTC, yokofms approved these changes
Looks good!

2023-06-28 12:15 UTC, merged